proposed fix for missing data object issue.
should fix this sporadic failure (happens between ~20-30% of the time when starting minions) when creating minions on aws:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cloud.py", line 399, in <lambda>
    target=lambda: self.create(tvm)
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cloud.py", line 206, in create
    ok = self.clouds['{0}.create'.format(self.provider(vm_))](vm_)
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/clouds/aws.py", line 240, in create
    while not data.public_ips:
AttributeError: 'NoneType' object has no attribute 'public_ips'